# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import game_events_pb2 as game__events__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TarkovMonitorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToGameEvents = channel.unary_stream(
                '/tarkovmonitor.v1.TarkovMonitorService/SubscribeToGameEvents',
                request_serializer=game__events__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=game__events__pb2.GameEvent.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/tarkovmonitor.v1.TarkovMonitorService/GetConfig',
                request_serializer=game__events__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=game__events__pb2.ServiceConfig.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/tarkovmonitor.v1.TarkovMonitorService/UpdateConfig',
                request_serializer=game__events__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=game__events__pb2.UpdateConfigResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/tarkovmonitor.v1.TarkovMonitorService/GetStatus',
                request_serializer=game__events__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=game__events__pb2.ServiceStatus.FromString,
                _registered_method=True)


class TarkovMonitorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubscribeToGameEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TarkovMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToGameEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToGameEvents,
                    request_deserializer=game__events__pb2.SubscriptionRequest.FromString,
                    response_serializer=game__events__pb2.GameEvent.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=game__events__pb2.GetConfigRequest.FromString,
                    response_serializer=game__events__pb2.ServiceConfig.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=game__events__pb2.UpdateConfigRequest.FromString,
                    response_serializer=game__events__pb2.UpdateConfigResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=game__events__pb2.GetStatusRequest.FromString,
                    response_serializer=game__events__pb2.ServiceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarkovmonitor.v1.TarkovMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarkovmonitor.v1.TarkovMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TarkovMonitorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeToGameEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tarkovmonitor.v1.TarkovMonitorService/SubscribeToGameEvents',
            game__events__pb2.SubscriptionRequest.SerializeToString,
            game__events__pb2.GameEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarkovmonitor.v1.TarkovMonitorService/GetConfig',
            game__events__pb2.GetConfigRequest.SerializeToString,
            game__events__pb2.ServiceConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarkovmonitor.v1.TarkovMonitorService/UpdateConfig',
            game__events__pb2.UpdateConfigRequest.SerializeToString,
            game__events__pb2.UpdateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarkovmonitor.v1.TarkovMonitorService/GetStatus',
            game__events__pb2.GetStatusRequest.SerializeToString,
            game__events__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
